name: We Are Family
favicon: null
layout_spectrum: 0.5825409758836031
typography_spectrum: 0.7102440614253283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.29746984387747943
  lightness: 0.5902143514249474
  saturation: 0.989560387795791
  rhythmicContrast: 0.17022255156189203
purpose: []
